name: concordi_around
description: ConcordiaAround is a campus guide mobile application for Concordia University
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_maps_flutter: 0.5.21+17
  geolocator: ^5.2.1
  flutter_typeahead: ^1.8.0
  flutter_svg: ^0.17.3+1
  provider: ^4.0.2
  dio: ^3.0.9
  uuid: ^2.0.4
  sliding_up_panel: ^1.0.0
  intl: ^0.16.0
  flutter_polyline_points: ^0.1.0
  html: ^0.14.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
  assets:
   - assets/floorplans/Hall-8.svg
   - assets/floorplans/Hall-9.svg
   - assets/map_style.json
   - assets/map_style_reset.json
   - assets/icon/
   - assets/direction_icon/