name: concordi_around
description: ConcordiaAround is a campus guide mobile application for Concordia University
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_maps_flutter: 0.5.21+17
  geolocator: ^5.2.1
  flutter_typeahead: ^1.8.0
  flutter_svg: 0.17.1
  provider: ^4.0.2
  dio: ^3.0.9
  uuid: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/floorplans/Hall-8.svg
   - assets/floorplans/Hall-9.svg
   - assets/map_style.json
   - assets/map_style_reset.json